spring:
  application:
    name: gateway_services
  cloud:
    gateway:
      routes:
        - id: create_user_route
          uri: http://localhost:8080
          predicates:
            - Path=/user/create
            - method=POST

        - id: login_user_route
          uri: http//localhost:8080
          predicates:
            - Path=/user/login
          filters:
            - AddRequestHeader=Authorization, Bearer

management:
  endpoints:
    web:
      exposure:
        include: "*"
